language: php

php:
    - 5.6
    - 7.0
    - 7.1
    
sudo: false

before_script:
    - composer install --prefer-dist

script:
    - bash test/sample_code_runner.sh
    - cat output.log

# For RoadRunner
#    - vendor/bin/phpunit test/RoadRunner.php
