language: php

php:
    - 5.6
    - 7.0
    - 7.1
    
sudo: false

before_script:
    - composer install --prefer-dist

script:
    - php Samples/Payments/CoreServices/ProcessPayment.php
    - php Samples/Payments/CoreServices/CapturePayment.php
    - php Samples/Payments/CoreServices/ProcessAuthorizationReversal.php
    - php Samples/Payments/CoreServices/ProcessCredit.php
    - php Samples/Payments/CoreServices/RefundCapture.php
    - php Samples/Payments/CoreServices/RefundPayment.php
